= Frequently Asked Questions on OpenWebStart
:imagesdir: ./images
:Author:    ...
:Email:     openwebstart@karakun.com
:Date:      ...
:Revision:  1.1.6
:toc:
:toclevels: 2

NOTE: The authors assume no responsibility or liability for any errors or omissions in the content of this documentation. The information contained in this documentation is provided on an "as is" basis with no guarantees of completeness, accuracy, usefulness, timeliness or of the results obtained from the use of this information.

== General

==== What is OpenWebStart?

#<this documentation is work in progress>#

== Subscription and Premium Support

==== Is there a subscription for OpenWebStart?
Basic subscription provided by Karakun is the cost-effective way to support OpenWebStart.
With this option, you may report bugs using a dedicated communication channel and your bug reports will have a higher priority.
If you wish, we will add your company logo to our sponsor list for free.
And you'll get a 10% discount for development of individual features.

==== Is there a premium support for OpenWebStart?
With premium support provided by Karakun you may report bugs or issues using the premium communication channel.
Your bug reports will have the highest priority.
Karakun will guarantee reaction times depending on the severity of bugs (during business hours).
Plus, you'll get a 25% discount for the development of individual features.
Upon your wish, your company logo will be listed as a premium sponsor on our website.

==== What are the costs for subscription and premium support?

To figure out which support model fits best to your needs, you should contact openwebstart@karakun.com.

== Installation

#<this documentation is work in progress>#

== Functionality

==== Does OpenWebStart support Applets?
Applets are not supported and there are no plans to support them in the future. We also do not consider this as a deviation from the JNLP-standard as this is an optional feature according to the JSR-56 specs.

==== Is there a MSI installer for OpenWebStart?
Currently we do not provide a MSI installer. More details on the reasons can be found at https://github.com/karakun/OpenWebStart/issues/98