= The Defintive Guide To OpenWebStart
:imagesdir: ./images
:Author:    The OWS Community
:Date:      4/2020
:Revision:  1.1.7
:toc:
:toclevels: 4

== Introduction

#<this documentation is work in progress>#

=== What is OpenWebStart?

#<this documentation is work in progress>#

== Installation

#<this documentation is work in progress>#

=== Basic Installation

=== Unattended Installation

OWS also offers an unattended installation mode which is useful when you have to install OWS on many computers.
Instead of walking through the graphical installer of OWS on every machine you can provide the options as a response file.

#<add more details as on the homepage>#

== Updates

OpenWebStart can be configured to automatically check for new releases and perform automatic updates.

To do so go to the "Updates" Panel in the OWS Settings.
It is possible to define an update strategy on every `start`, `daily`, `weekly`, `monthly`, or `never`.

== Configuration

#<this documentation is work in progress>#

=== JVM Manager

#<TODO: describe OWS settings options>#

==== JVM Download Server

OpenWebStart can fetch JVMs and JVM updates from a download server that is specified in the JVM Manager Configuration of the OWS Settings application.
The default points to `https://download-openwebstart.com/jvms.json`.

==== Setup a Custom Download Server
If you want to set up your own JVM download server you must provide a json file which lists all available JVMs.

This json file must contain the following data:

[source]
----
{
    "cacheTimeInMillis":<miliseconds>,
    "runtimes":[
        {
            "version":<JVM version>,
            "vendor":<vendor name>,
            "os":<OS identifier>,
            "href":<absolute url to the archive containing the JVM>
        },

        ... more runtime definitions
}

----

cacheTimeInMillis:: The time which needs to elapse before a client is allowed to contact the server again. Usually the server is accessed once per application startup.

os:: Possible values are: MAC64, MAC32, LINUX64, LINUX32, WIN64, WIN32

=== Cache Management

#<TODO: describe OWS settings options>#

=== Proxy Settings

#<TODO: describe OWS settings options>#

=== Certificates

#<TODO: describe OWS settings options>#

=== Security Settings

#<TODO: describe OWS settings options>#

=== Server Whitelists

The "Server Whitelists" panel in OWS settings displays the server whitelist.
To define a server whitelist you have to edit the `deployment.properties` file in your config directory with a text editor by adding a new line similar to the following:

[source]
----
deployment.security.whitelist=10.10.10.10, google.com, some.server.net
----

The different servers are listed as a comma separated string.
Localhost is implicitly always in the white list.
If you delete the line again then no whitelisting is applied and all servers are reachable.

Note that whitelisting only applies while downloading resources (jars and jnlps) and not while an application is running.
Thus an application can open a connection to a server which is not in the white list.

It is also possible to specify the content of the whitelist in the response file of an unattended OWS installation.

=== Logging

#<TODO: describe OWS settings options>#

=== Remote Debugging

#<TODO: describe OWS settings options>#

=== Centralized Configuration

- list all the properties that allows to configure a centralized installation (Terminalserver)

