= The Definitive Guide To OpenWebStart
:imagesdir: ./images
:Author:    The OWS Community
:Date:      7/2020
:Revision:  1.1.8
:toc:
:toclevels: 4

== Introduction

Java Web Start (JWS) was deprecated in Java 9, and starting with Java 11, Oracle removed JWS from their JDK distributions. This means that clients that have the latest version of Java installed can no longer use JWS-based applications. And since public support of Java 8 has ended in Q2/2019, companies no longer get any updates and security fixes for Java Web Start.

This is why some enthusiasts at Karakun decided to create OpenWebStart, an open source reimplementation of the Java Web Start technology. This guide describes how you can use OpenWebStart as a replacement for JWS and continue using your JNLP-based applications  with little or no change at all.

We appreciate your feedback. If you feel that there's a lack of documentation in a certain area or if you find inaccuracies in the documentation, please don't hesitate to contact us at openwebstart@karakun.com or the  https://board.karakun.com/viewforum.php?f=4[support forum].

=== What is OpenWebStart?

OpenWebStart is an open source reimplementation of the Java Web Start technology, released under the GPL with Classpath Exception. It provides the most commonly used features of Java Web Start and the JNLP standard, so that your customers can continue using applications based on Java Web Start and JNLP without any change. OpenWebStart is based on Iced-Tea-Web and follows the JNLP-specification defined in JSR-56.

The main focus of OpenWebStart is the execution of JNLP-based applications. Additionally, the tool contains various modules that simplify your Web Start workflows and let you configure OpenWebStart to suit your needs:

App Manager:: manages the versions of any JNLP-based application that is executed by OpenWebStart.

JVM Manager:: manages Java versions and Java updates on the client.

Control Panel:: provides a graphical user interface to configure OpenWebStart.

Updater:: downloads and installs new versions of OpenWebStart.

== Installation
OpenWebStart can be installed on Windows, MacOS and Linux operating systems and there are two different ways to install OpenWebStart:

* Using the *interactive installation* with auto-update functionality
* Using the *unattended installation* for automated roll-outs

If you use Web Start for several small customers or on your own, we recommend using the interactive installer. Our native installer will set up everything on your Windows, Mac, or Linux system so that OpenWebStart is immediately ready to use. OpenWebStart checks for updates automatically, and the Updater component keeps the tool current without the need for any user interaction.

If you or your customers are companies with IT departments of their own, we recommend an unattended installation to roll out OpenWebStart on multiple client machines. In this scenario, the auto-update functionality is inactive; your IT department is free to plan and handle rollouts of new versions based on your internal workflows.

=== Interactive Installation

==== Windows

 1. Open the ZIP-file.
 1. Run the installer.
 1. Choose a language and click *OK* to open the OpenWebStart Setup wizard.
 1. Click *Next* to start the OpenWebStart installation.
 1. Browse to the directory where to install OpenWebStart, and click *Next*. +
    Windows default: `C:\Program Files\OpenWebStart`
 1. Enable the checkbox to associate the .JNLP suffix with OpenWebStart, and click *Next*.
 1. Please wait for OpenWebStart to be installed on your computer.
 1. Click *Finish* on the completion screen to close the wizard.

==== macOS

1. Open the OpenWebStart disk image (DMG file) to mount it.
1. Run the `Open Web Start Installer.app`.
1. Choose a language and click *OK* to open the OpenWebStart Setup wizard.
1. Click *Next* to start the OpenWebStart installation.
1. Browse to the directory where to install OpenWebStart, and click *Next*. +
   Default: `/Applications/Open Web Start`
1. Enable the checkbox to associate the .JNLP suffix with OpenWebStart, and click *Next*.
1. Please wait for OpenWebStart to be installed on your computer.
1. Click *Finish* on the completion screen to close the wizard.

==== Linux

1. Go to the directory where the installer (DEB file) is stored and run the file from the terminal +
   `sudo dpkg -i OpenWebStart_linux_1_1_8.deb`
1. Enter your root password.
1. Choose a language and click OK to open the OpenWebStart Setup wizard.
1. Click Next to start the OpenWebStart installation.
1. Browse to the directory where to install OpenWebStart, and click Next. +
   Default: `/opt/openwebstart`
1. Enable the checkbox to associate the .JNLP suffix with OpenWebStart, and click Next.
1. Please wait for OpenWebStart to be installed on your computer.
1. Click Finish on the completion screen to close the wizard.

If you need help installing OpenWebStart, also have a look at the public installation and configuration discussions at the https://board.karakun.com/viewforum.php?f=10[Support Forum].

=== Unattended Installation

OWS also offers an unattended installation mode which is useful when you have to install OWS on many computers.
Instead of walking through the graphical installer of OWS on every machine you can provide the options as a response file.

#<add more details as on the homepage>#

== Updates

OpenWebStart can be configured to automatically check for new releases and perform automatic updates.

To do so go to the "Updates" Panel in the OWS Settings.
It is possible to define an update strategy on every `start`, `daily`, `weekly`, `monthly`, or `never`.

== Configuration

There is an extra application to configure OpenWebStart.
The executable is located in the installation directory and is named `itw-settings`.

All settings are stored on the file system.
For Windows the file is located at `${USER_HOME}\.config\icedtea-web\deployment.properties`.
For Mac and Linux the file is located at `${USER_HOME}/.config/icedtea-web/deployment.properties`.
This file can be edited with a regular text editor.
For some expert configurations this may be necessary but for most cases the graphical UI will be sufficient.

Besides the per user configuration there exists also the possibility to define a system wide configuration.
This allows setting up a common configuration for multiple users on a single computer.
Or helps in managing a corporate infrastructure where many computers need to be configured identically.

For more details see the sections below.

=== JVM Manager

#<TODO: describe OWS settings options>#

==== JVM Download Server

OpenWebStart can fetch JVMs and JVM updates from a download server that is specified in the JVM Manager Configuration of the OWS Settings application.
The default points to `https://download-openwebstart.com/jvms.json`.

==== Setup a Custom Download Server
If you want to set up your own JVM download server you must provide a json file which lists all available JVMs.

This json file must contain the following data:

[source]
----
{
    "cacheTimeInMillis":<miliseconds>,
    "runtimes":[
        {
            "version":<JVM version>,
            "vendor":<vendor name>,
            "os":<OS identifier>,
            "href":<absolute url to the archive containing the JVM>
        },

        ... more runtime definitions
}

----

cacheTimeInMillis:: The time which needs to elapse before a client is allowed to contact the server again. Usually the server is accessed once per application startup.

os:: Possible values are: MAC64, MAC32, LINUX64, LINUX32, WIN64, WIN32

=== Cache Management

#<TODO: describe OWS settings options>#

=== Proxy Settings

#<TODO: describe OWS settings options>#

=== Certificates

#<TODO: describe OWS settings options>#

=== Security Settings

#<TODO: describe OWS settings options>#

=== Server Whitelists

The "Server Whitelists" panel in OWS settings displays the server whitelist.
To define a server whitelist you have to edit the `deployment.properties` file in your config directory with a text editor by adding a new line similar to the following:

[source]
----
deployment.security.whitelist=10.10.10.10, google.com, some.server.net
----

The different servers are listed as a comma separated string.
Localhost is implicitly always in the white list.
If you delete the line again then no whitelisting is applied and all servers are reachable.

Note that whitelisting only applies while downloading resources (jars and jnlps) and not while an application is running.
Thus an application can open a connection to a server which is not in the white list.

It is also possible to specify the content of the whitelist in the response file of an unattended OWS installation.

=== Logging

#<TODO: describe OWS settings options>#

=== Remote Debugging

#<TODO: describe OWS settings options>#

=== System Configuration

When loading the configuration during the start of OpenWebStart the following steps are executed:

1. Load the default values which are hardcoded in the source code.
1. Search for a system configuration.
1. Load the system configuration if one was found.
1. Load the user configuration.

Whenever a configuration is loaded the values which are already defined are updated.
There is however the possibility to lock a property.
If a property is locked then subsequent configurations may not modify the value.
This allows enforcing certain values on a system level.
Any changes the user makes in his personal configuration file will not have any effect on the locked property.

==== Defining the System Configuration

The system configuration needs to be defined in the following way.

*Windows:* create the file `%windir%\Sun\Java\deployment\deployment.config` and add the following properties:

*MacOs and Linux:* create the file `/etc/.java/deployment/deployment.config` and add the following properties:

deployment.system.config:: The URL to the system configuration.
The name of the file can be freely chosen.
Special characters need escaping.
See the following examples:
* `deployment.system.config=file\:/C\:/Window/Sun/Java/global.properties`
* `deployment.system.config=file\:/etc/.java/deployment/base.properties`
* `deployment.system.config=https\:192.168.1.1./javaws/system.properties`

deployment.system.config.mandatory:: If set to `true` then OpenWebStart will fail if it is unable to load the system settings
This property is optional.
The default value is `false`.

The final file should look something like this:

[source]
----
deployment.system.config=https\:192.168.1.1./javaws/system.properties
deployment.system.config.mandatory=true
----

==== Content of the System Configuration

The simplest way to create a system configuration is to start the `itw-settings`.
After saving the configuration the modified properties are written to the user configuration file.
For Windows the file is located at `${USER_HOME}\.config\icedtea-web\deployment.properties`.
For Mac and Linux the file is located at `${USER_HOME}/.config/icedtea-web/deployment.properties`.

The customized user configuration can be used as a starting point for the system configuration.
Simply copy the file and remove the properties which should not be defined on the system level.

OpenWebStart does not save properties which have the default value.
Therefore the generated user configuration may not contain all the values you wish to enforce on the system level.

Please contact openwebstart@karakun.com if you need to know the key and valid values for a specific configuration.

==== Locking a property

One of the use cases is to enforce some configurations to all users in your corporate environment.
This can be achieved by locking configuration on a system level.
To lock a property you need to define a second entry with a `.locked` postfix.

Here an example:

[source]
----
ows.jvm.manager.server.default=https\://192.168.1.1/jvms.json
ows.jvm.manager.server.default.locked=true
----

TIP: the value of `ows.jvm.manager.server.default.locked` is ignored.
The presence of the key is sufficient for locking the property.
